# Generated by Django 4.2.16 on 2024-11-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('select', 'Dropdown'), ('file', 'File Upload')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('choices', models.TextField(blank=True, help_text='Enter choices separated by commas (for radio/select)')),
                ('order', models.IntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='vehicles.inspection')),
            ],
            options={
                'db_table': 'inspection_fields',
            },
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vehicles.inspection')),
            ],
            options={
                'db_table': 'inspection_responses',
            },
        ),
        migrations.CreateModel(
            name='InspectionFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.inspectionfield')),
                ('inspection_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='vehicles.inspectionresponse')),
            ],
            options={
                'db_table': 'inspection_field_responses',
            },
        ),
    ]
