# Generated by Django 4.2.17 on 2024-12-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='case_ref',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missionassignedemployee',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='scheduling.mission'),
        ),
    ]
