# Generated by Django 4.2.17 on 2024-12-07 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car')], max_length=20, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('on_route', 'On Route'), ('maintenance', 'Maintenance'), ('available', 'Available'), ('out_of_service', 'Out of Service')], max_length=20, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('fuel_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('on_trip', models.BooleanField(default=False)),
                ('mileage', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('after_market', models.BooleanField(default=False)),
                ('purchased_at', models.DateField()),
                ('delivered_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_part',
            },
        ),
        migrations.CreateModel(
            name='AssetPartManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asset_part_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='AssetPartSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('purchase_url', models.URLField()),
                ('notes', models.TextField()),
                ('purchase_location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'asset_part_supplier',
            },
        ),
        migrations.CreateModel(
            name='AssetPartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asset_part_type',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('asset_type', models.CharField(blank=True, choices=[('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car')], max_length=20, null=True)),
                ('reg_number', models.CharField(max_length=20)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(max_length=20)),
                ('findings', models.JSONField(default=list)),
                ('next_inspection', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('select', 'Dropdown'), ('file', 'File Upload')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('choices', models.TextField(blank=True, help_text='Enter choices separated by commas (for radio/select)')),
                ('order', models.IntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='maintenance.inspection')),
            ],
            options={
                'db_table': 'inspection_fields',
            },
        ),
        migrations.CreateModel(
            name='InspectionStatus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inspection_statuses',
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inspection_types',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inspection_locations',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePriority',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenance_priorities',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenance_statuses',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenance_types',
            },
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='maintenance.inspection')),
            ],
            options={
                'db_table': 'inspection_responses',
            },
        ),
        migrations.CreateModel(
            name='InspectionFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.inspectionfield')),
                ('inspection_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='maintenance.inspectionresponse')),
            ],
            options={
                'db_table': 'inspection_field_responses',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.location'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='ref_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.inspectionstatus'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.inspectiontype'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reg_number', models.CharField(max_length=20)),
                ('asset_type', models.CharField(blank=True, choices=[('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car')], max_length=20, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('mechanic', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_duration', models.CharField(max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parts', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.location')),
                ('previous_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenance')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancepriority')),
                ('ref_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.asset')),
                ('ref_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.inspection')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancestatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetype')),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['reg_number'], name='maintenance_reg_num_3a1aab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['reg_number'], name='inspections_reg_num_1939ce_idx'),
        ),
    ]
