# Generated by Django 4.2.17 on 2024-12-07 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Workshop A', 'Workshop A'), ('Workshop B', 'Workshop B'), ('Workshop C', 'Workshop C'), ('Workshop D', 'Workshop D'), ('Workshop E', 'Workshop E')], max_length=50)),
                ('equipment', models.JSONField(default=list, help_text='List of available equipment')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
            ],
            options={
                'db_table': 'maintenance_bays',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.JSONField(help_text='List of days when this window is active (0=Monday, 6=Sunday)')),
                ('location', models.CharField(choices=[('Workshop A', 'Workshop A'), ('Workshop B', 'Workshop B'), ('Workshop C', 'Workshop C'), ('Workshop D', 'Workshop D'), ('Workshop E', 'Workshop E')], max_length=50)),
            ],
            options={
                'db_table': 'maintenance_windows',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency_rating', models.FloatField(help_text="Rating between 0-1 indicating mechanic's efficiency", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'db_table': 'mechanics',
            },
        ),
        migrations.CreateModel(
            name='MechanicSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mechanic_skills',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, choices=[('On Route', 'On Route'), ('Maintenance', 'Maintenance'), ('Available', 'Available'), ('Out of Service', 'Out of Service')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MechanicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(help_text='Percentage of time available in this window', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.mechanic')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancewindow')),
            ],
            options={
                'db_table': 'mechanic_availability',
            },
        ),
        migrations.AddField(
            model_name='mechanic',
            name='availability',
            field=models.ManyToManyField(through='maintenance.MechanicAvailability', to='maintenance.maintenancewindow'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='skills',
            field=models.ManyToManyField(to='maintenance.mechanicskill'),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancebay')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.mechanic')),
            ],
            options={
                'db_table': 'maintenance_schedules',
            },
        ),
    ]
