# Generated by Django 4.2.17 on 2024-12-07 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancebay_maintenancewindow_mechanic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetPartManufacturer',
        ),
        migrations.DeleteModel(
            name='AssetPartType',
        ),
        migrations.AddField(
            model_name='asset',
            name='capacity_volume',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='capacity_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='assetpart',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('oem', 'OEM'), ('bosch', 'Bosch'), ('denso', 'Denso'), ('delphi', 'Delphi'), ('valeo', 'Valeo'), ('continental', 'Continental')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetpart',
            name='part_type',
            field=models.CharField(blank=True, choices=[('engine', 'Engine'), ('transmission', 'Transmission'), ('brakes', 'Brakes'), ('suspension', 'Suspension'), ('electrical', 'Electrical'), ('body', 'Body')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='maintenance.mechanicskill'),
        ),
        migrations.AlterField(
            model_name='maintenancebay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
